import {db} from '../storage/db';import {localDate} from '../core/dates';import {CATALOG,CARPENTER_IMPROVEMENTS,STARTER_BUILDINGS,dailyStock} from './catalog';import {canPlace,rewardForEvent} from './rules';import {SETTLEMENT_GRID,buildingWorldObject,canPlaceWorld,entranceClearance} from './world';import type {BuildingType} from './types';
const now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
export async function bootstrapGame(){await db.transaction('rw',db.gameState,db.buildings,db.npcProgress,async()=>{if(!await db.gameState.get('singleton'))await db.gameState.add({id:'singleton',currency:0,settlementLevel:1,createdAt:now()});if(await db.buildings.count()===0)await db.buildings.bulkAdd(STARTER_BUILDINGS);for(const b of STARTER_BUILDINGS)if(!await db.npcProgress.get(b.type))await db.npcProgress.add({id:b.type,met:false,interactionCount:0,relationshipLevel:0})});await syncProductivityRewards()}
export async function syncProductivityRewards(){const events=await db.productivityEvents.toArray();await db.transaction('rw',db.gameState,db.gameLedger,async()=>{const state=await db.gameState.get('singleton');if(!state)return;let currency=state.currency;for(const e of events){const ledgerId=`earn:${e.id}`;if(await db.gameLedger.get(ledgerId))continue;const amount=rewardForEvent(e);if(amount<=0)continue;await db.gameLedger.add({id:ledgerId,kind:'EARN',amount,sourceId:e.id,sourceType:e.type,createdAt:now()});currency+=amount}await db.gameState.update('singleton',{currency})})}
async function spend(amount:number,sourceId:string,sourceType:string){const state=await db.gameState.get('singleton');if(!state||state.currency<amount)throw new Error('Not enough Spark');const ledgerId=`spend:${sourceId}`;if(await db.gameLedger.get(ledgerId))throw new Error('Already purchased');await db.gameLedger.add({id:ledgerId,kind:'SPEND',amount:-amount,sourceId,sourceType,createdAt:now()});await db.gameState.update('singleton',{currency:state.currency-amount})}
export async function buyItem(catalogItemId:string){const item=CATALOG.find(i=>i.id===catalogItemId);if(!item)throw new Error('Unknown item');const shop=await db.buildings.where('type').equals(item.shop).first();if(!shop?.built||shop.level<item.minShopLevel)throw new Error('Item locked');const purchaseId=`item:${catalogItemId}:${uid()}`;await db.transaction('rw',db.gameState,db.gameLedger,db.ownedItems,async()=>{await spend(item.price,purchaseId,'SHOP_PURCHASE');await db.ownedItems.add({id:purchaseId,catalogItemId,acquiredAt:now(),quantity:1})})}
export async function buyCarpenterImprovement(improvementId:string){const imp=CARPENTER_IMPROVEMENTS.find(x=>x.id===improvementId);if(!imp)throw new Error('Unknown improvement');const b=await db.buildings.where('type').equals(imp.target).first();if(!b)throw new Error('Building missing');if(imp.kind==='CLEAR'&&!b.overgrown)throw new Error('Already cleared');if(imp.kind==='BUILD'&&b.built)throw new Error('Already built');if(imp.kind==='UPGRADE'&&(!b.built||b.level!==(imp as any).minLevel))throw new Error('Upgrade unavailable');await db.transaction('rw',db.gameState,db.gameLedger,db.buildings,async()=>{await spend(imp.price,imp.id,'CARPENTER');if(imp.kind==='CLEAR')await db.buildings.update(b.id,{overgrown:false});if(imp.kind==='BUILD')await db.buildings.update(b.id,{built:true,level:1});if(imp.kind==='UPGRADE')await db.buildings.update(b.id,{level:b.level+1})})}
export async function moveBuilding(buildingId:string,x:number,y:number){const b=await db.buildings.get(buildingId);if(!b?.built)return false;const all=(await db.buildings.toArray()).filter(o=>o.built);const others=all.filter(o=>o.id!==b.id).map(buildingWorldObject);const zones=all.filter(o=>o.id!==b.id).map(o=>entranceClearance(o));const candidate=buildingWorldObject({...b,x,y});if(!canPlaceWorld(candidate,others,zones,SETTLEMENT_GRID))return false;await db.buildings.update(b.id,{x,y});return true}
export async function placeOwnedItem(ownedItemId:string,x:number,y:number){const owned=await db.ownedItems.get(ownedItemId);if(!owned)return false;const item=CATALOG.find(i=>i.id===owned.catalogItemId);if(!item?.width||!item.height)return false;const existing=await db.placedItems.where('ownedItemId').equals(ownedItemId).first();const others=(await db.placedItems.where('area').equals('HOME').toArray()).filter(p=>p.id!==existing?.id);const candidate={x,y,width:item.width,height:item.height};if(!canPlace(candidate,others,10,8))return false;if(existing)await db.placedItems.update(existing.id,candidate);else await db.placedItems.add({id:uid(),ownedItemId,area:'HOME',...candidate});return true}
export async function meetNpc(type:BuildingType){const p=await db.npcProgress.get(type);if(!p)return;const n=p.interactionCount+1;await db.npcProgress.update(type,{met:true,interactionCount:n,relationshipLevel:Math.min(3,Math.floor(n/5))})}
export function furnitureStock(date=localDate(),level=1){return{permanent:CATALOG.filter(i=>i.shop==='FURNITURE_STORE'&&i.permanent&&i.minShopLevel<=level),daily:dailyStock('FURNITURE_STORE',date,level,4)}}
