import {useEffect,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../storage/db';
import {bootstrap,completeOccurrence,createActivity,makeTodayRestDay,reflect,setIntention,updateSettings} from '../application/service';
import {localDate} from '../core/dates';
import {isDeliberateDay,taskPointsForDay} from '../core/rules';
import {downloadBackup,restoreBackup,validateBackup} from '../storage/backup';
import type {DomainOutcome,EffortTier,RecurrenceType,ThemeId,Weekday} from '../core/types';
import './style.css';

const THEMES:{id:ThemeId;name:string;note:string}[]=[
 {id:'MOONLIT_SANCTUARY',name:'Moonlit Sanctuary',note:'Calm · Focused · Mystical'},
 {id:'SUNLIT_GROVE',name:'Sunlit Grove',note:'Warm · Encouraging · Alive'},
 {id:'EMBER_STONE',name:'Ember & Stone',note:'Bold · Grounded · Resilient'},
 {id:'CELESTIAL_MINIMAL',name:'Celestial Minimal',note:'Clean · Modern · Focused'},
 {id:'TWILIGHT_BLOOM',name:'Twilight Bloom',note:'Whimsical · Cozy · Inspiring'},
];
const THEME_CLASS:Record<ThemeId,string>={MOONLIT_SANCTUARY:'moonlit',SUNLIT_GROVE:'sunlit',EMBER_STONE:'ember',CELESTIAL_MINIMAL:'celestial',TWILIGHT_BLOOM:'twilight'};
const DOMAIN_MARKS=['◐','◇','◎','△'];

export default function App(){
 const [ready,setReady]=useState(false);const [tab,setTab]=useState<'today'|'tasks'|'reflect'|'settings'>('today');
 useEffect(()=>{bootstrap().then(()=>setReady(true))},[]);
 const data=useLiveQuery(async()=>({settings:await db.settings.get('singleton'),day:await db.dayRecords.where('localDate').equals(localDate()).first(),domains:await db.domains.orderBy('displayOrder').toArray(),intentions:await db.intentions.toArray(),reflections:await db.reflections.toArray(),occurrences:await db.occurrences.toArray(),activities:await db.activities.toArray()}),[ready]);
 if(!ready||!data?.day||!data.settings)return <main className="loading">Loading…</main>;
 const settings={...data.settings,theme:data.settings.theme??'MOONLIT_SANCTUARY' as ThemeId};const today=data.day;const points=taskPointsForDay(today.localDate,data.occurrences);const deliberate=isDeliberateDay(today,data.domains,data.intentions,data.reflections,data.occurrences);const todays=data.occurrences.filter(o=>o.status==='PENDING'&&((o.effectiveStart<=today.localDate&&o.effectiveEnd>=today.localDate)||o.effectiveEnd<today.localDate));const completed=data.occurrences.filter(o=>o.status==='COMPLETED'&&o.completedEffectiveDate===today.localDate);
 const screen=tab==='settings'?<Settings settings={settings}/>:tab==='tasks'?<TasksScreen todays={todays} completed={completed} date={today.localDate}/>:tab==='reflect'?<ReflectionScreen domains={data.domains} dayId={today.id} intentions={data.intentions} reflections={data.reflections}/>:<Today settings={settings} today={today} points={points} deliberate={deliberate} domains={data.domains} intentions={data.intentions} reflections={data.reflections} todays={todays} completed={completed}/>;
 return <div className={`app theme-${THEME_CLASS[settings.theme]}`}><div className="ambient"/><main>{screen}</main><nav className="bottom-nav" aria-label="Primary"><Nav active={tab==='today'} onClick={()=>setTab('today')} label="Today" mark="⌂"/><Nav active={tab==='tasks'} onClick={()=>setTab('tasks')} label="Tasks" mark="☑"/><Nav active={tab==='reflect'} onClick={()=>setTab('reflect')} label="Reflect" mark="◌"/><Nav active={tab==='settings'} onClick={()=>setTab('settings')} label="Settings" mark="•••"/></nav></div>
}
function Nav({active,onClick,label,mark}:{active:boolean;onClick:()=>void;label:string;mark:string}){return <button className={active?'active':''} onClick={onClick}><span>{mark}</span>{label}</button>}
function Today({settings,today,points,deliberate,domains,intentions,reflections,todays,completed}:any){const pct=Math.min(100,Math.round(points/today.taskPointTargetSnapshot*100));return <>
 <header className="mantra-card"><span className="eyebrow">MANTRA</span><textarea aria-label="Mantra" value={settings.mantra} placeholder="What do you want to remember?" onChange={e=>updateSettings({mantra:e.target.value})}/><span className="mantra-rule"/></header>
 <section className="section domains-section"><div className="section-title"><div><span className="eyebrow">TODAY</span><h2>Your intentions</h2></div><span className="date-label">{prettyDate(today.localDate)}</span></div><div className="domains">{domains.map((d:any,i:number)=><DomainCard key={d.id} domain={d} mark={DOMAIN_MARKS[i]} dayId={today.id} intentions={intentions} reflections={reflections}/>)}</div></section>
 <section className="section tasks-section"><div className="section-title"><div><span className="eyebrow">TASKS</span><h2>Move today forward</h2></div><strong className="points">{points} / {today.taskPointTargetSnapshot}</strong></div><div className="progress"><i style={{width:`${pct}%`}}/></div>{deliberate&&<div className="deliberate">Deliberate Day complete</div>}<TaskForm/><TaskList items={todays} date={today.localDate}/><details className="completed"><summary>Completed <b>{completed.length}</b></summary>{completed.map((o:any)=><div className="done" key={o.id}><span className="check checked">✓</span><span>{o.nameSnapshot}</span><b>{o.pointValueSnapshot} pt{o.pointValueSnapshot===1?'':'s'}</b></div>)}</details></section>
 </>}
function DomainCard({domain,mark,dayId,intentions,reflections}:any){const i=intentions.find((x:any)=>x.dayId===dayId&&x.domainId===domain.id);const r=i&&reflections.find((x:any)=>x.intentionId===i.id);const [text,setText]=useState('');return <article className={`domain-card ${r?'reflected':''}`}><div className="domain-head"><span className="domain-mark">{mark}</span><h3>{domain.name}</h3></div>{!i?<><input className="intention-input" placeholder="Set intention…" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&text.trim())setIntention(dayId,domain.id,text)}}/><button className="text-button" disabled={!text.trim()} onClick={()=>setIntention(dayId,domain.id,text)}>Set intention</button></>:<><p>{i.text}</p>{r&&<small>✓ {r.outcome==='NOT_TODAY'?'Not Today':r.outcome==='PARTIAL'?'Partially':'Achieved'}</small>}</>}</article>}
function TaskList({items,date}:{items:any[];date:string}){return <div className="tasks">{items.length===0?<p className="empty">Nothing waiting here. Add something when you're ready.</p>:items.map(o=><button className="task" key={o.id} onClick={()=>completeOccurrence(o.id,date)}><span className="check"/><span className="task-copy"><b>{o.nameSnapshot}</b>{o.descriptionSnapshot&&<small>{o.descriptionSnapshot}</small>}{o.effectiveEnd<date&&<em>Overdue</em>}</span><span className="task-points">{o.pointValueSnapshot}</span></button>)}</div>}
function TasksScreen({todays,completed,date}:any){return <><PageHeader eyebrow="TASKS" title="Your task list" subtitle="Everything actionable today, in one calm place."/><section className="section"><TaskForm/><TaskList items={todays} date={date}/><details className="completed" open><summary>Completed <b>{completed.length}</b></summary>{completed.map((o:any)=><div className="done" key={o.id}><span className="check checked">✓</span><span>{o.nameSnapshot}</span><b>{o.pointValueSnapshot}</b></div>)}</details></section></>}
function ReflectionScreen({domains,dayId,intentions,reflections}:any){return <><PageHeader eyebrow="REFLECT" title="How did today go?" subtitle="Notice what happened. No grading, no minimum word count."/><section className="section reflection-list">{domains.map((d:any,i:number)=><ReflectionCard key={d.id} domain={d} mark={DOMAIN_MARKS[i]} dayId={dayId} intentions={intentions} reflections={reflections}/>)}</section></>}
function ReflectionCard({domain,mark,dayId,intentions,reflections}:any){const i=intentions.find((x:any)=>x.dayId===dayId&&x.domainId===domain.id);const r=i&&reflections.find((x:any)=>x.intentionId===i.id);const [text,setText]=useState('');const [outcome,setOutcome]=useState<DomainOutcome>('ACHIEVED');return <article className="reflection-card"><div className="domain-head"><span className="domain-mark">{mark}</span><h3>{domain.name}</h3></div>{!i?<p className="muted">No intention was set for this domain today.</p>:r?<><p className="intention-quote">“{i.text}”</p><div className="reflection-done">{r.outcome==='NOT_TODAY'?'Not Today':r.outcome==='PARTIAL'?'Partially':'Achieved'} · {r.text}</div></>:<><p className="intention-quote">“{i.text}”</p><div className="segmented">{(['ACHIEVED','PARTIAL','NOT_TODAY'] as DomainOutcome[]).map(o=><button className={outcome===o?'selected':''} key={o} onClick={()=>setOutcome(o)}>{o==='NOT_TODAY'?'Not Today':o==='PARTIAL'?'Partially':'Achieved'}</button>)}</div><textarea placeholder="A short reflection…" value={text} onChange={e=>setText(e.target.value)}/><button className="primary" disabled={!text.trim()} onClick={()=>reflect(i.id,outcome,text)}>Save reflection</button></>}</article>}
function Settings({settings}:{settings:any}){return <><PageHeader eyebrow="SETTINGS" title="Make it yours" subtitle="Your data stays local. Appearance changes never touch your history."/><section className="section"><h2>Appearance</h2><p className="muted">Theme</p><div className="theme-grid">{THEMES.map(t=><button key={t.id} className={`theme-option ${settings.theme===t.id?'selected':''}`} onClick={()=>updateSettings({theme:t.id})}><span className={`theme-preview preview-${THEME_CLASS[t.id]}`}><i/><i/><i/></span><span><b>{t.name}</b><small>{t.note}</small></span>{settings.theme===t.id&&<strong>✓</strong>}</button>)}</div></section><section className="section settings-stack"><h2>Daily defaults</h2><label>Daily point target <input type="number" min="1" value={settings.defaultTaskPointTarget} onChange={e=>updateSettings({defaultTaskPointTarget:Number(e.target.value)})}/></label><button className="secondary" onClick={makeTodayRestDay}>Make Today an Intentional Rest Day</button></section><section className="section settings-stack"><h2>Your data</h2><button className="secondary" onClick={downloadBackup}>Save Backup</button><label className="file secondary">Restore Backup<input type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const b=JSON.parse(await f.text());if(!validateBackup(b))return alert('Invalid backup');if(confirm('Replace local data with this validated backup?')){await restoreBackup(b);location.reload()}}}/></label></section></>}
function PageHeader({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <header className="page-header"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></header>}
function TaskForm(){const [open,setOpen]=useState(false);const [name,setName]=useState('');const [description,setDescription]=useState('');const [effort,setEffort]=useState<EffortTier>('STANDARD');const [repeat,setRepeat]=useState<RecurrenceType>('NONE');const [when,setWhen]=useState(localDate());const [weekdays,setWeekdays]=useState<Weekday[]>([]);async function add(){await createActivity({name,description,effortTier:effort,recurrence:{type:repeat,weekdays:repeat==='SPECIFIC_WEEKDAYS'?weekdays:undefined},startDate:when,scheduledDate:repeat==='NONE'?when:undefined});setName('');setDescription('');setOpen(false)}return <div className="task-form-wrap">{!open?<button className="add-task" onClick={()=>setOpen(true)}>＋ Add task</button>:<div className="form"><input autoFocus placeholder="Task name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Small description (optional)" value={description} onChange={e=>setDescription(e.target.value)}/><div className="form-row"><select value={effort} onChange={e=>setEffort(e.target.value as EffortTier)}><option value="SMALL">Small · 1</option><option value="STANDARD">Standard · 2</option><option value="MAJOR">Major · 3</option></select><input type="date" value={when} onChange={e=>setWhen(e.target.value)}/></div><select value={repeat} onChange={e=>setRepeat(e.target.value as RecurrenceType)}><option value="NONE">Doesn't repeat</option><option value="DAILY">Every day</option><option value="WEEKLY">Every week</option><option value="SPECIFIC_WEEKDAYS">Specific days</option></select>{repeat==='SPECIFIC_WEEKDAYS'&&<div className="weekday-row">{['S','M','T','W','T','F','S'].map((x,i)=><button key={i} className={weekdays.includes(i as Weekday)?'selected':''} onClick={()=>setWeekdays(w=>w.includes(i as Weekday)?w.filter(n=>n!==i):[...w,i as Weekday])}>{x}</button>)}</div>}<div className="form-actions"><button className="primary" disabled={!name.trim()||(repeat==='SPECIFIC_WEEKDAYS'&&!weekdays.length)} onClick={add}>Add task</button><button className="text-button" onClick={()=>setOpen(false)}>Cancel</button></div></div>}</div>}
function prettyDate(s:string){return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${s}T12:00:00`))}
