import {db} from '../storage/db';
import {addDays,localDate,previousDay} from '../core/dates';
import {bounceBackEligible,expectedPeriod,isDeliberateDay,occurrenceKey,snapshotOccurrence} from '../core/rules';
import type {ActivityVersion,DomainOutcome,EffortTier,LocalDate,RecurrenceRule,ThemeId,Weekday} from '../core/types';
import {bootstrapGame,syncProductivityRewards} from '../game/service';
const id=()=>crypto.randomUUID(); const now=()=>new Date().toISOString();
export async function bootstrap(){await db.transaction('rw',db.settings,db.domains,db.metadata,async()=>{if(!await db.settings.get('singleton'))await db.settings.add({id:'singleton',mantra:'',defaultTaskPointTarget:10,theme:'MOONLIT_SANCTUARY'});if(await db.domains.count()===0)await db.domains.bulkAdd(['Spiritual','Mental','Social / Emotional','Physical'].map((name,i)=>({id:id(),name,displayOrder:i})));await db.metadata.put({key:'schemaVersion',value:'1'})});await ensureDay(localDate());await ensureOccurrencesThrough(localDate());await bootstrapGame();}
export async function ensureDay(date:LocalDate){let d=await db.dayRecords.where('localDate').equals(date).first();if(d)return d;const s=await db.settings.get('singleton');d={id:id(),localDate:date,taskPointTargetSnapshot:s?.defaultTaskPointTarget??10,dayType:'NORMAL'};await db.dayRecords.add(d);return d}
export async function createActivity(input:{name:string;description?:string;effortTier:EffortTier;recurrence:RecurrenceRule;startDate:LocalDate;scheduledDate?:LocalDate}){const activityId=id();await db.transaction('rw',db.activities,db.activityVersions,async()=>{await db.activities.add({id:activityId,createdAt:now()});await db.activityVersions.add({id:id(),activityId,effectiveFrom:input.startDate,...input})});await ensureOccurrencesThrough(localDate());return activityId}
export async function ensureOccurrencesThrough(date:LocalDate){const activities=await db.activities.toArray();for(const a of activities){if(a.archivedAt)continue;const versions=(await db.activityVersions.where('activityId').equals(a.id).sortBy('effectiveFrom'));if(!versions.length)continue;let cursor=versions[0].startDate;while(cursor<=date){const v=[...versions].reverse().find(x=>x.effectiveFrom<=cursor);if(v){const p=expectedPeriod(v,cursor);if(p){const key=occurrenceKey(a.id,p.start,p.end);const exists=await db.occurrences.where('[activityId+effectiveStart+effectiveEnd]').equals([a.id,p.start,p.end]).first();if(!exists)await db.occurrences.add(snapshotOccurrence(v,p.start,p.end,key))}}cursor=addDays(cursor,1)}}}
export async function completeOccurrence(occurrenceId:string,effectiveDate?:LocalDate){await db.transaction('rw',db.occurrences,db.productivityEvents,async()=>{const o=await db.occurrences.get(occurrenceId);if(!o||o.status==='COMPLETED')return;const completedAt=now();const completionDate=effectiveDate??localDate();await db.occurrences.update(o.id,{status:'COMPLETED',completedAt,completedEffectiveDate:completionDate});await db.productivityEvents.put({id:`TASK_COMPLETED:${o.id}`,type:'TASK_COMPLETED',sourceId:o.id,effectiveDate:completionDate,recordedAt:completedAt,payload:{points:o.pointValueSnapshot},version:1})});await syncProductivityRewards();await evaluateDeliberateDay((await db.dayRecords.where('localDate').equals(effectiveDate??localDate()).first())?.id??'');}
export async function setIntention(dayId:string,domainId:string,text:string){const existing=await db.intentions.where('[dayId+domainId]').equals([dayId,domainId]).first();if(existing)throw new Error('Intention already set for this domain/day');await db.intentions.add({id:id(),dayId,domainId,text:text.trim(),createdAt:now()})}
export async function reflect(intentionId:string,outcome:DomainOutcome,text:string){await db.transaction('rw',db.reflections,db.productivityEvents,db.intentions,db.dayRecords,async()=>{if(await db.reflections.where('intentionId').equals(intentionId).first())throw new Error('Reflection already recorded');const r={id:id(),intentionId,outcome,text:text.trim(),recordedAt:now()};await db.reflections.add(r);const i=await db.intentions.get(intentionId);if(i&&outcome!=='NOT_TODAY'){const type=outcome==='ACHIEVED'?'DOMAIN_ACHIEVED':'DOMAIN_PARTIALLY_ACHIEVED';const day=await db.dayRecords.get(i.dayId);if(day)await db.productivityEvents.put({id:`${type}:${intentionId}`,type,sourceId:intentionId,effectiveDate:day.localDate,recordedAt:r.recordedAt,version:1})}});await evaluateDeliberateDayByIntention(intentionId);await syncProductivityRewards()}
async function evaluateDeliberateDayByIntention(intentionId:string){const i=await db.intentions.get(intentionId);if(i)await evaluateDeliberateDay(i.dayId)}
export async function evaluateDeliberateDay(dayId:string){const [day,domains,intentions,reflections,occurrences]=await Promise.all([db.dayRecords.get(dayId),db.domains.toArray(),db.intentions.toArray(),db.reflections.toArray(),db.occurrences.toArray()]);if(day&&isDeliberateDay(day,domains,intentions,reflections,occurrences))await db.productivityEvents.put({id:`DELIBERATE_DAY_COMPLETED:${day.id}`,type:'DELIBERATE_DAY_COMPLETED',sourceId:day.id,effectiveDate:day.localDate,recordedAt:now(),version:1});await syncProductivityRewards()}
export async function archiveActivity(activityId:string){await db.activities.update(activityId,{archivedAt:now()})}
export async function restoreActivity(activityId:string){await db.activities.update(activityId,{archivedAt:null});await ensureOccurrencesThrough(localDate())}
export async function makeTodayRestDay(){const today=await ensureDay(localDate());await db.dayRecords.update(today.id,{dayType:'INTENTIONAL_REST'});await evaluateDeliberateDay(today.id)}
export async function updateSettings(patch:{mantra?:string;defaultTaskPointTarget?:number;theme?:ThemeId}){const s=await db.settings.get('singleton');if(!s)return;await db.settings.put({...s,...patch})}
export async function closeYesterday(){const y=await db.dayRecords.where('localDate').equals(previousDay(localDate())).first();if(y)await db.dayRecords.update(y.id,{closedAt:now()})}
